### PR TITLE
fix: Combine plots

### PR DESCRIPTION
**Pull request by coolalexzb**
This PR aims to fix bugs and changes in PR #24

### CODE REVIEW

**Comment by coolalexzb** [comment]
@matthewfeickert What is the possible reason for the Install dependencies problem in `CI / test (ubuntu-latest, 3.8)` ?

**Comment by matthewfeickert** [comment]
> What is the possible reason for the Install dependencies problem in `CI / test (ubuntu-latest, 3.8)` ?

It isn't you or anything that you're doing, just that GitHub Actions is having some problems with downloading large libraries like TensorFlow and PyTorch. This has been reported to GitHub Engineering by various people, so hopefully things get better in the next few weeks.

**Comment by matthewfeickert** [comment]
I missed this earlier when I was trying to do review, so I'll just link my comment that I put on PR 24 (sorry): https://github.com/pyhf/pyhf-benchmark/pull/24/files#r464648390

I'd try to focus on having functions do more simple things, such as just create the `subplots` objects and then return them. You can then more easily manipulate them and then reduce the number of things you need to pass around as the directory stuff is just for saving them out and that isn't necessarily the same as the actual plotting. So I'd try to refactor that a bit.

**Comment by matthewfeickert** [comment]
> It isn't you or anything that you're doing, just that GitHub Actions is having some problems with downloading large libraries like TensorFlow and PyTorch. This has been reported to GitHub Engineering by various people, so hopefully things get better in the next few weeks.

This is now https://github.com/actions/virtual-environments/issues/1354

**Pull request merged**
